/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface PullPaymentInterface extends ethers.utils.Interface {
  functions: {
    "payments(address)": FunctionFragment;
    "withdrawPayments(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "payments", values: [string]): string;
  encodeFunctionData(
    functionFragment: "withdrawPayments",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPayments",
    data: BytesLike
  ): Result;

  events: {};
}

export class PullPayment extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: PullPaymentInterface;

  functions: {
    payments(
      dest: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "payments(address)"(
      dest: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    withdrawPayments(
      payee: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawPayments(address)"(
      payee: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  payments(dest: string, overrides?: CallOverrides): Promise<BigNumber>;

  "payments(address)"(
    dest: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawPayments(
    payee: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawPayments(address)"(
    payee: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    payments(dest: string, overrides?: CallOverrides): Promise<BigNumber>;

    "payments(address)"(
      dest: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawPayments(payee: string, overrides?: CallOverrides): Promise<void>;

    "withdrawPayments(address)"(
      payee: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    payments(dest: string, overrides?: CallOverrides): Promise<BigNumber>;

    "payments(address)"(
      dest: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawPayments(payee: string, overrides?: Overrides): Promise<BigNumber>;

    "withdrawPayments(address)"(
      payee: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    payments(
      dest: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "payments(address)"(
      dest: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawPayments(
      payee: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawPayments(address)"(
      payee: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
